In [ ]:
tensorflow_version

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [ ]:
path_to_file =r'shakespeare.txt'

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving shakespeare.txt to shakespeare.txt


In [ ]:
text = open(path_to_file,'r').read()

In [ ]:
print(text[:5000])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bud buriest thy content,
  And tender churl mak'st waste in niggarding:
    Pity the world, or else this glutton be,
    To eat the world's due, by the grave and thee.


                     2
  When forty winters shall besiege thy brow,
  And dig deep trenches in thy beauty's field,
  Thy youth's proud livery so gazed on now,
  Will be a tattered weed of small worth held:  
  Then being asked, where all thy beauty lies,
  Where all the treasure of thy lusty days;
  To say within thine own deep su

In [ ]:
vocab = sorted(set(text))
print(vocab)
len(vocab)

['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '>', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '|', '}']


84

In [ ]:
char_to_ind = {u:i for i, u in enumerate(vocab)}
char_to_ind
ind_to_char =np.array(vocab)

In [ ]:
ind_to_char

array(['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1',
       '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '>', '?',
       'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
       '[', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i',
       'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
       'w', 'x', 'y', 'z', '|', '}'], dtype='<U1')

In [ ]:
encoded_text = np.array([char_to_ind[c] for c in text])

In [ ]:
encoded_text

array([ 0,  1,  1, ..., 30, 39, 29])

In [ ]:
sample = text[:20]
sample

'\n                   '

In [ ]:
encoded_text[:20]

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
#creating batches

print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [ ]:
line = "From fairest creatures we desire increase"

In [ ]:
len(line)

41

In [ ]:
part_stanza = """From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,"""

In [ ]:
len(part_stanza)

131

In [ ]:
seq_len = 120

In [ ]:
total_num_seq = len(text)//(seq_len+1)

In [ ]:
total_num_seq

45005

In [ ]:
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)
for i in char_dataset.take(500):
    print(ind_to_char[i.numpy()])



 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
1


 
 
F
r
o
m
 
f
a
i
r
e
s
t
 
c
r
e
a
t
u
r
e
s
 
w
e
 
d
e
s
i
r
e
 
i
n
c
r
e
a
s
e
,


 
 
T
h
a
t
 
t
h
e
r
e
b
y
 
b
e
a
u
t
y
'
s
 
r
o
s
e
 
m
i
g
h
t
 
n
e
v
e
r
 
d
i
e
,


 
 
B
u
t
 
a
s
 
t
h
e
 
r
i
p
e
r
 
s
h
o
u
l
d
 
b
y
 
t
i
m
e
 
d
e
c
e
a
s
e
,


 
 
H
i
s
 
t
e
n
d
e
r
 
h
e
i
r
 
m
i
g
h
t
 
b
e
a
r
 
h
i
s
 
m
e
m
o
r
y
:


 
 
B
u
t
 
t
h
o
u
 
c
o
n
t
r
a
c
t
e
d
 
t
o
 
t
h
i
n
e
 
o
w
n
 
b
r
i
g
h
t
 
e
y
e
s
,


 
 
F
e
e
d
'
s
t
 
t
h
y
 
l
i
g
h
t
'
s
 
f
l
a
m
e
 
w
i
t
h
 
s
e
l
f
-
s
u
b
s
t
a
n
t
i
a
l
 
f
u
e
l
,


 
 
M
a
k
i
n
g
 
a
 
f
a
m
i
n
e
 
w
h
e
r
e
 
a
b
u
n
d
a
n
c
e
 
l
i
e
s
,


 
 
T
h
y
 
s
e
l
f
 
t
h
y
 
f
o
e
,
 
t
o
 
t
h
y
 
s
w
e
e
t
 
s
e
l
f
 
t
o
o
 
c
r
u
e
l
:


 
 
T
h
o
u
 
t
h
a
t
 
a
r
t
 
n
o
w
 
t
h
e
 
w
o
r
l
d
'
s
 
f
r
e
s
h
 
o
r
n
a
m
e
n
t
,


 
 
A
n
d
 
o
n
l
y
 
h
e
r
a
l
d
 
t
o
 
t
h
e
 
g
a
u
d
y
 
s
p
r
i
n
g
,


 
 
W
i
t
h
i
n
 
t
h
i
n
e
 
o
w
n
 
b
u


In [ ]:
sequences = char_dataset.batch(seq_len+1, drop_remainder=True)

In [ ]:
def create_seq_targets(seq):
  input_txt = seq[:-1]
  target_txt = seq[1:]
  return input_txt, target_txt

In [ ]:
dataset = sequences.map(create_seq_targets)

In [ ]:
for input_txt, target_txt in dataset.take(1):
  print(input_txt.numpy())
  print(''.join(ind_to_char[input_txt.numpy()]))
  print('\n')
  print(target_txt.numpy())
  print(''.join(ind_to_char[target_txt.numpy()]))

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But


[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1]
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But 


In [ ]:
batch_size =128
buffer_size = 1000
dataset=dataset.shuffle(buffer_size).batch(batch_size, drop_remainder=True)

In [ ]:
dataset

<_BatchDataset element_spec=(TensorSpec(shape=(128, 120), dtype=tf.int64, name=None), TensorSpec(shape=(128, 120), dtype=tf.int64, name=None))>

In [ ]:
vocab_size = len(vocab)

In [ ]:
embed_dim =64

In [ ]:
rnn_neurons = 1026

In [ ]:
from tensorflow.keras.models import Sequential

In [ ]:
from tensorflow.keras.layers import LSTM,Dense,Embedding,Dropout,GRU
from tensorflow.keras import Input # Added Input import

In [ ]:
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [ ]:
help(sparse_categorical_crossentropy)

Help on function sparse_categorical_crossentropy in module keras.src.losses.losses:

sparse_categorical_crossentropy(y_true, y_pred, from_logits=False, ignore_class=None, axis=-1)
    Computes the sparse categorical crossentropy loss.

    Args:
        y_true: Ground truth values.
        y_pred: The predicted values.
        from_logits: Whether `y_pred` is expected to be a logits tensor. By
            default, we assume that `y_pred` encodes a probability distribution.
        ignore_class: Optional integer. The ID of a class to be ignored during
            loss computation. This is useful, for example, in segmentation
            problems featuring a "void" class (commonly -1 or 255) in
            segmentation maps. By default (`ignore_class=None`), all classes are
            considered.
        axis: Defaults to `-1`. The dimension along which the entropy is
            computed.

    Returns:
        Sparse categorical crossentropy loss value.

    Examples:

    >>> y_true =

In [ ]:
def sparse_cat_loss(y_true,y_pred):
  return sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)

In [ ]:
def create_model(vocab_size, embed_dim, rnn_neurons, batch_size):
  model = Sequential()
  model.add(Input(batch_shape=(batch_size, None)))
  model.add(Embedding(vocab_size, embed_dim))
  model.add(GRU(rnn_neurons,return_sequences=True,stateful=True,recurrent_initializer='glorot_uniform'))
  model.add(Dense(vocab_size))
  model.compile(optimizer='adam', loss=sparse_cat_loss)
  return model

In [ ]:
  model = create_model(
      vocab_size = vocab_size,
      embed_dim = embed_dim,
      rnn_neurons = rnn_neurons,
      batch_size = batch_size)

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (128, None, 64)        │         5,376 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru (GRU)                       │ (128, None, 1026)      │     3,361,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (128, None, 84)        │        86,268 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,452,820 (13.17 MB)

 Trainable params: 3,452,820 (13.17 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
for input_example_batch, target_example_batch in dataset.take(1):
  example_batch_predictions = model(input_example_batch)
  print(example_batch_predictions.shape, " <=== (batch_size, sequence_length, vocab_size)")

(128, 120, 84)  <=== (batch_size, sequence_length, vocab_size)


In [ ]:
example_batch_predictions

<tf.Tensor: shape=(128, 120, 84), dtype=float32, numpy=
array([[[ 4.35085036e-03,  2.65564024e-03,  5.32379886e-03, ...,
         -2.93701817e-03, -3.64406058e-03,  5.86711708e-03],
        [ 4.27604566e-04,  5.74662304e-03,  4.34074504e-03, ...,
         -2.82119540e-03,  2.79608788e-03,  9.79123637e-03],
        [-1.78009202e-03, -1.14347335e-04, -3.52457282e-03, ...,
          2.95853382e-03, -4.13610600e-04,  6.40862621e-04],
        ...,
        [ 2.98375351e-04,  5.15655009e-03,  1.51824832e-04, ...,
         -5.23096556e-03,  1.01940194e-02,  6.62634289e-03],
        [ 3.10809328e-03, -3.07626528e-04, -1.70752150e-03, ...,
         -4.27738763e-03, -2.34970311e-03,  1.34654464e-02],
        [ 2.43679504e-03, -3.34123708e-03, -8.59809481e-03, ...,
          4.69167763e-03,  3.97316093e-04,  1.30376569e-03]],

       [[-1.60309207e-03,  4.32921399e-04,  3.18536069e-03, ...,
         -8.24540015e-03,  2.52600061e-03,  6.23272965e-04],
        [-3.00755701e-03,  6.33876771e-04,  3.2

In [ ]:
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)

In [ ]:
sampled_indices

<tf.Tensor: shape=(120, 1), dtype=int64, numpy=
array([[48],
       [79],
       [77],
       [55],
       [32],
       [31],
       [47],
       [ 1],
       [21],
       [73],
       [73],
       [67],
       [14],
       [77],
       [43],
       [26],
       [65],
       [15],
       [37],
       [31],
       [46],
       [ 4],
       [48],
       [37],
       [18],
       [51],
       [72],
       [ 1],
       [24],
       [15],
       [83],
       [26],
       [79],
       [49],
       [47],
       [13],
       [41],
       [46],
       [76],
       [27],
       [60],
       [12],
       [43],
       [52],
       [36],
       [ 2],
       [77],
       [43],
       [68],
       [29],
       [80],
       [70],
       [83],
       [42],
       [19],
       [72],
       [25],
       [22],
       [38],
       [53],
       [30],
       [63],
       [ 1],
       [ 3],
       [67],
       [71],
       [ 2],
       [74],
       [17],
       [14],
       [64],
       [74],
       [19],
   

In [ ]:
sampled_indices = tf.squeeze(sampled_indices,axis=-1).numpy()

In [ ]:
sampled_indices

array([48, 79, 77, 55, 32, 31, 47,  1, 21, 73, 73, 67, 14, 77, 43, 26, 65,
       15, 37, 31, 46,  4, 48, 37, 18, 51, 72,  1, 24, 15, 83, 26, 79, 49,
       47, 13, 41, 46, 76, 27, 60, 12, 43, 52, 36,  2, 77, 43, 68, 29, 80,
       70, 83, 42, 19, 72, 25, 22, 38, 53, 30, 63,  1,  3, 67, 71,  2, 74,
       17, 14, 64, 74, 19,  1, 38, 42, 73, 68, 49,  1, 41, 36, 11,  0, 26,
       26, 10, 56, 68, 12, 19, 34, 75,  7, 28, 79, 38, 73, 19, 45, 70,  4,
        4, 18, 20, 34,  8, 44, 81, 10, 27, 81, 46, 38, 12,  7, 34, 17, 64,
        8])

In [ ]:
print("Given the input seq: \n")
print("".join(ind_to_char[input_example_batch[0]]))
print('\n')
print("Next Char Predictions: \n")
print("".join(ind_to_char[sampled_indices ]))

Given the input seq: 

are to the ground;
  And for the peace of you I hold such strife
  As 'twixt a miser and his wealth is found.
  Now prou


Next Char Predictions: 

Wxv`GFV :rrl3vRAj4LFU&WL7Zq >4}AxXV2PUuBe1R[K!vRmDyo}Q8q?;M]Eh "lp!s63is8 MQrmX PK0
AA.am18It)CxMr8To&&79I,Sz.BzUM1)I6i,


In [ ]:
epochs = 30

In [ ]:
model.fit(dataset,epochs=epochs)

Epoch 1/30
351/351 ━━━━━━━━━━━━━━━━━━━━ 53s 145ms/step - loss: 2.9196
Epoch 2/30
351/351 ━━━━━━━━━━━━━━━━━━━━ 61s 174ms/step - loss: 1.6887
Epoch 3/30
351/351 ━━━━━━━━━━━━━━━━━━━━ 60s 170ms/step - loss: 1.4486
Epoch 4/30
351/351 ━━━━━━━━━━━━━━━━━━━━ 60s 172ms/step - loss: 1.3397
Epoch 5/30
351/351 ━━━━━━━━━━━━━━━━━━━━ 61s 173ms/step - loss: 1.2805
Epoch 6/30
351/351 ━━━━━━━━━━━━━━━━━━━━ 60s 172ms/step - loss: 1.2428
Epoch 7/30
351/351 ━━━━━━━━━━━━━━━━━━━━ 60s 172ms/step - loss: 1.2122
Epoch 8/30
351/351 ━━━━━━━━━━━━━━━━━━━━ 61s 172ms/step - loss: 1.1894
Epoch 9/30
351/351 ━━━━━━━━━━━━━━━━━━━━ 84s 177ms/step - loss: 1.1697
Epoch 10/30
351/351 ━━━━━━━━━━━━━━━━━━━━ 61s 172ms/step - loss: 1.1514
Epoch 11/30
351/351 ━━━━━━━━━━━━━━━━━━━━ 60s 171ms/step - loss: 1.1363
Epoch 12/30
351/351 ━━━━━━━━━━━━━━━━━━━━ 61s 173ms/step - loss: 1.1214
Epoch 13/30
351/351 ━━━━━━━━━━━━━━━━━━━━ 61s 172ms/step - loss: 1.1081
Epoch 14/30
351/351 ━━━━━━━━━━━━━━━━━━━━ 60s 172ms/step - loss: 1.0965
Epoch 15/30
351

In [ ]:
model.save('shakespeare_gen.h5')

In [ ]:
from tensorflow.keras.models import load_model

In [ ]:
model = create_model(vocab_size, embed_dim, rnn_neurons, batch_size=1)

In [ ]:
model.load_weights('shakespeare_gen.h5')
model.build(tf.TensorShape([1, None]))

In [ ]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (1, None, 64)          │         5,376 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_1 (GRU)                     │ (1, None, 1026)        │     3,361,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (1, None, 84)          │        86,268 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,452,820 (13.17 MB)

 Trainable params: 3,452,820 (13.17 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
def generate_text(model, start_seed,gen_size=100,temp=1.0):
  num_generate = gen_size
  input_eval = [char_to_ind[s] for s in start_seed]
  input_eval = tf.expand_dims(input_eval, 0)
  text_generated = []
  temperature = temp

  for i in range(num_generate):
    predictions = model(input_eval)
    predictions = tf.squeeze(predictions, 0)
    predictions = predictions / temperature
    predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()
    input_eval = tf.expand_dims([predicted_id], 0)
    text_generated.append(ind_to_char[predicted_id])
  return (start_seed + ''.join(text_generated))

In [ ]:
print(generate_text(model,"flower",gen_size=1000))

flower,
    Being angry.
  CAMILLO. I am sure, and may be sacrificed.
    N you honour, here you may
    do.
  FLORIZEL. So I derive.
  PHORUS. O, why, sid, now let me have! afterwards been a man's hand
    That I have since yet break with my descent!
    The King's pristy minds,
    Even in this presence still. Fie,
    Though you can find your trick of illy wedded,
    You shall be publish'd with this beard; and sometimes it
    of Phoebus nature, fathom again.
  LEONTES. Those of Rithme.
  AGUECHEEK. An if that it writ, I wish that which your pronouncer be.
  SHEPHERD. How have you yourselves!
  CAMILLO. Mistress is noight; Imoget so. Write it, so I'll none
    And you have chain'd. Sobell in silence,
  Am in the swift with prov'd so needy,
  Nothing but the blood, and commanded now
    That I shall drown whom most not-met gallop's the pit. You must die; yet all
    that this fair power, sir? your son without a thousand sorport she
    vadour they will.
  CLOWN. Truly, Master Page, 